// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA72t5LU0lWsFCsw2rgE8xSdpaoGRmV88',
    appId: '1:691790513374:web:83c47064f5bc8964a52e4f',
    messagingSenderId: '691790513374',
    projectId: 'todo-app-54f2d',
    authDomain: 'todo-app-54f2d.firebaseapp.com',
    storageBucket: 'todo-app-54f2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAup5qeXTZWhoQlU5yn4411YMlT9FZIDU8',
    appId: '1:691790513374:android:882d1fd33ed110eda52e4f',
    messagingSenderId: '691790513374',
    projectId: 'todo-app-54f2d',
    storageBucket: 'todo-app-54f2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjE-YMgfXErGfgwRKHxAww4NaHndUesdc',
    appId: '1:691790513374:ios:7fd71a6bc4273ccda52e4f',
    messagingSenderId: '691790513374',
    projectId: 'todo-app-54f2d',
    storageBucket: 'todo-app-54f2d.firebasestorage.app',
    iosBundleId: 'com.ebpearls.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjE-YMgfXErGfgwRKHxAww4NaHndUesdc',
    appId: '1:691790513374:ios:7fd71a6bc4273ccda52e4f',
    messagingSenderId: '691790513374',
    projectId: 'todo-app-54f2d',
    storageBucket: 'todo-app-54f2d.firebasestorage.app',
    iosBundleId: 'com.ebpearls.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA72t5LU0lWsFCsw2rgE8xSdpaoGRmV88',
    appId: '1:691790513374:web:58a86c27614626daa52e4f',
    messagingSenderId: '691790513374',
    projectId: 'todo-app-54f2d',
    authDomain: 'todo-app-54f2d.firebaseapp.com',
    storageBucket: 'todo-app-54f2d.firebasestorage.app',
  );
}
